import React from "react";
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "@fontsource/playfair-display/400.css";
import "@fontsource/playfair-display/600-italic.css";
import "@fontsource/playfair-display/700-italic.css";
import "./globals.css";
import Footer from "../components/Footer";
import ClientNavbarWrapper from "../components/ClientNavbarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plan C Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientNavbarWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}





